# Stub — StorageBackend Protocol (будет расширен в Phase 2)
from typing import Protocol


class StorageBackend(Protocol):
    def write_file(self, filepath: str, content: str, metadata: dict | None = None) -> None: ...
    def read_file(self, filepath: str) -> tuple[dict, str]: ...
    def create_snapshot(self, label: str = "") -> str: ...
    def restore_snapshot(self, snapshot_name: str) -> bool: ...
